targets:
  $default:
    sources:
      - lib/**
    builders:
      json_serializable:
        options:
          include_if_null: false
      artemis:
        options:
          custom_parser_import: lib/time_parser.dart
          scalar_mapping:
            - graphql_type: DateTime
              dart_type: DateTime
              use_custom_parser: true
          schema_mapping:
            - schema: lib/schema.graphql
              queries_glob: lib/graphql/football_api.graphql
              output: lib/dart/football_api.graphql.dart
